### ISSUE TITLE
`_.each` 无法遍历对象

### ISSUE THREAD

**Issue by cubxx** [RaymondClr/Soil#1]
函数签名和 jsdoc 中的示例不一样，无法遍历对象

**Comment by RaymondClr** [comment]
1、首先这确实是我个人失误导致的错误，很抱歉，因为 lodash jsdoc 部分照搬了原内容，没有及时从 each 中移除对迭代对象的支持。
2、soil 为了确保类型推导精确，严格区分了数组和对象的迭代方法，由于是纯 ts 开发，不同于 lodash  js + .d.ts 的套壳操作，如果为了兼容对象，使用重载，会使函数内部的类型推导趋于混乱和复杂，而不得不使用 any 弥补。如果确实要遍历对象，应该使用正统的 _.forOwn。
